# Generated by Django 6.0.7 on 2026-09-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authz", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="grantaudit",
            name="on_behalf_of",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
